apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignored
  labels:
    accepts-neighbours: true
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: accepts-neighbours
            operator: In
            values:
            - false
        topologyKey: topology.kubernetes.io/zone
