apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../bases/common
  - azure-storage-class.yaml
  - azure-storage-azure-disk.yaml
  - minio-data-pv-claim.yaml
  - postgresql-data-pv-claim.yaml
  - postgresql-service.yaml
  - minio-get-storage-data-pv-claim.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: gridcapa-rabbitmq
      spec:
        volumeClaimTemplates:
          - metadata:
              name: gridcapa-rabbitmq-data
            spec:
              storageClassName: azure-storage-class
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: "5Gi"
  - target:
      kind: Deployment
      name: gridcapa-minio
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          # Since Minio 2022, a url has to be set here even though it is not used
          # However, this causes troubles on Coreso environment so we only add it on Azure
          name: MINIO_BROWSER_REDIRECT_URL
          value: "http://minio.local/minio/"