apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: gridcapa-highest-priority
value: 1000
globalDefault: false
description: "Priority for pods that must start first"

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: gridcapa-medium-priority
value: 500
globalDefault: false
description: "Priority for pods that start after the highest priority pods"
