apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../bases/common
  - ../../../bases/cse-common
  - postgresql-deployment.yaml
  - postgresql-service.yaml
  - minio-get-storage-data-pv-claim.yaml


patches:
  #  Patch affinities for rao runners
  - target:
      kind: Deployment
      labelSelector: "component = rao-runner"
    path: patches/rao-runner-affinity-patch.yaml

  # Patches for high priority
  - target:
      kind: Deployment
      labelSelector: "component in ( gateway, gridcapa-minio, postgresql )"
    path: patches/high-priority-patch.yaml
  - target:
      kind: StatefulSet
      labelSelector: "component = gridcapa-rabbitmq"
    path: patches/high-priority-patch-statefulset.yaml
