apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../bases/common
  - ../../../bases/cse-common
  - postgresql-deployment.yaml
  - postgresql-service.yaml
  - minio-get-storage-data-pv-claim.yaml


patches:
  - patch: |-
      kind: CronJob
      apiVersion: batch/v1
      metadata:
        name: minio-get-storage-data-cron
        labels:
          app: gridcapa
          component: minio-get-storage-data
      spec:
        suspend: true