CREATE DATABASE config;
CREATE USER config_server WITH ENCRYPTED PASSWORD 'config';
GRANT ALL PRIVILEGES ON DATABASE config TO config_server;
CREATE DATABASE cse_idcc_tasks;
CREATE USER cse_idcc_server WITH ENCRYPTED PASSWORD 'cse-idcc';
GRANT ALL PRIVILEGES ON DATABASE cse_idcc_tasks TO cse_idcc_server;
CREATE DATABASE cse_d2cc_tasks;
CREATE USER cse_d2cc_server WITH ENCRYPTED PASSWORD 'cse-d2cc';
GRANT ALL PRIVILEGES ON DATABASE cse_d2cc_tasks TO cse_d2cc_server;
CREATE DATABASE core_valid_tasks;
CREATE USER core_valid_server WITH ENCRYPTED PASSWORD 'core-valid';
GRANT ALL PRIVILEGES ON DATABASE core_valid_tasks TO core_valid_server;